parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    HashCash\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    HashCash\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    HashCash\LambdaInvoker\LambdaInvokerInterface:
        class: HashCash\LambdaInvoker\ExecLambdaInvoker